name: Build

permissions:
  packages: write
  contents: write
  
on:
  push:
      branches:
      - main
jobs:
  my_jobs:
    name: deploy to staging
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run: mkdir artifact/PhysicsGame/
        
      - name: Copy the executable to the artifact directory
        run: copy Build/PhysicsGame/Release/Win32/PhysicsGame.exe artifact/PhysicsGame/

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2 
        with: 
          path: artifact/PhysicsGame/
     
  release:
    needs: my_jobs
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5.0.0
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        
      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3

  
